language: go
go_import_path: github.com/zg1211/config
env:
  - GOMAXPROCS=4
matrix:
  include:
    - go: 1.10.x
      install:
        - go get github.com/stretchr/testify/assert
        - go get gopkg.in/yaml.v2
      script:
        - go test -race -v ./...
    - go: 1.11.x
      install:
        - go get github.com/stretchr/testify/assert
        - go get gopkg.in/yaml.v2
      script:
        - go test -race -v ./...
